[project]
name = "integracao-embrace"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Eduardo Augusto Rabelo Socca", email = "eduardo_socca@yahoo.com.br" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "pandas>=3.0.5",
    "pycap>=2.7.0",
    "python-dotenv>=1.2.3",
    "python-multipart>=0.0.32",
    "requests>=2.34.2",
    "uvicorn>=0.52.3",
]

[project.scripts]
integracao-embrace = "integracao_embrace:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"
